# Archivo: netlify.toml (en la raíz del repositorio)

[build]
  base = "client" 
  command = "npm install && ng build --configuration production --base-href /"
  
  # CORRECCIÓN CLAVE: Debe ser relativa a la carpeta "client"
  publish = "dist/client" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200